# 1. Write a NumPy program to get the numpy version and show numpy build configuration

In [3]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/DELL/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\li

# 2. Write a NumPy program to get help on the add function.

In [4]:
import numpy as np
print(help(np.add))

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

# 3.Write a NumPy program to test whether none of the elements of a given array is zero.

In [37]:
import numpy as np
a = np.array([[1,2,3,1],[2,3,4,5],[12,13,15,16]])
b = np.array([[1,2,3,1],[2,3,4,5],[0,0,0,0]])
if a.all() :
    print("None of the elements are zero")
else :
    print("There is an elements that contains zero")
    

None of the elements are zero


# 4. Write a NumPy program to test whether any of the elements of a given array is non-zero

In [45]:
import numpy as np
a = np.array([[1,2,3,1],[2,3,4,5],[12,13,15,16]])
b = np.array([[0,0,0],[0,0,0],[0,0,0]])
if a.any() :
    print("There are elements that are non-zero")
else :
    print("There are no elements that are non-zero")
    

There are elements that are non-zero


# 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).


In [50]:
import numpy as np
a = np.array([[1,2,3,np.nan],[2,3,4,-np.inf],[12,13,15,16]])
print(np.isfinite(a))

[[ True  True  True False]
 [ True  True  True False]
 [ True  True  True  True]]


# 6.  Write a NumPy program to test element-wise for positive or negative infinity.


In [53]:
import numpy as np
a = np.array([[1,2,3,np.inf],[2,3,4,-np.inf],[12,13,15,np.nan]])
print(np.isinf(a))

[[False False False  True]
 [False False False  True]
 [False False False False]]


# 7. Write a NumPy program to test element-wise for NaN of a given array.


In [55]:
import numpy as np
a = np.array([[1,2,3+2j,np.inf],[2,3,4,-np.inf],[12,13,15,np.nan]])
print(np.isnan(a))

[[False False False False]
 [False False False False]
 [False False False  True]]


# 8. Write a NumPy program to test element-wise for complex numbers, real numbers of a given array. Also test whether a given number is a scalar type or not

In [80]:
import numpy as np
a = np.array([[1,2,3+3j,np.inf],[2,3,4,-np.inf],[12,13,15,np.nan]])
print("Checking for complex numbers:\n",np.iscomplex(a))
print("Checking for real numbers:\n",np.isreal(a))
print("Checking for scalar numbers:\n",np.isscalar(2.5))


Checking for complex numbers:
 [[False False  True False]
 [False False False False]
 [False False False False]]
Checking for real numbers:
 [[ True  True False  True]
 [ True  True  True  True]
 [ True  True  True  True]]
Checking for scalar numbers:
 True


# 9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance

# 10.Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.


In [90]:
import numpy as np
a = np.array([[1,2,3,4],[2,3,4,5],[12,13,15,12]])
b = np.array([[1,2,3,11],[2,3,4,-21],[12,3,5,2]])
c = [1,2,3]
d = [1,2,3]
print("Checking for greater numbers:\n",np.greater(a,b))
print("Checking for greater_equal numbers:\n",np.greater_equal(c,d))
print("Checking for less numbers:\n",np.less(a,b))
print("Checking for less numbers:\n",np.less_equal(c,d))


Checking for greater numbers:
 [[False False False False]
 [False False False  True]
 [False  True  True  True]]
Checking for greater_equal numbers:
 [ True  True  True]
Checking for less numbers:
 [[False False False  True]
 [False False False False]
 [False False False False]]
Checking for less numbers:
 [ True  True  True]


# 11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [25]:
import numpy as np
a = np.array([[1,2,3,4],[2,3,4,5],[12,13,15,12]])
b = np.array([[1,2,3,11],[2,3,4,-21],[12,3,5,2]])
c = [1,2,3]
d = [1,2,3]
print("Checking for greater numbers:\n",np.greater(a,3))
print("Checking for greater_equal numbers:\n",np.greater_equal(c,4))
print("Checking for less numbers:\n",np.less(a,1))
print("Checking for less numbers:\n",np.less_equal(c,3))


Checking for greater numbers:
 [[False False False  True]
 [False False  True  True]
 [ True  True  True  True]]
Checking for greater_equal numbers:
 [False False False]
Checking for less numbers:
 [[False False False False]
 [False False False False]
 [False False False False]]
Checking for less numbers:
 [ True  True  True]


# 12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.


In [95]:
import numpy as np
a = np.array([1,7,13,105])
print("Size of memory occupied : ",a.size*a.itemsize)

Size of memory occupied :  16


# 13.Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [99]:
import numpy as np
print("Array of 10 zeros: ",np.zeros(10))
print("Array of 10 ones: ",np.ones(10))
print("Array of 10 fives: ",np.ones(10)*5)

Array of 10 zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives:  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# 14. Write a NumPy program to create an array of the integers from 30 to70.

In [101]:
import numpy as np
print("Array of integers from 30 to 70 : ",np.arange(30,70))

Array of integers from 30 to 70 :  [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


# 15. Write a NumPy program to create an array of all the even integers from 30 to 70.


In [102]:
import numpy as np
print("Array of integers from 30 to 70 : ",np.arange(30,70,2))

Array of integers from 30 to 70 :  [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


# 16. Write a NumPy program to create a 3x3 identity matrix.


In [103]:
import numpy as np
a=np.identity(3)
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 17. Write a NumPy program to generate a random number between 0 and 1.

In [119]:
import numpy as np
print("Random number between 0 and 1:",np.random.normal(0,1,1))

Random number between 0 and 1: [1.22503237]


# 18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.


In [122]:
import numpy as np
print("Random number between 1 and 15:",np.random.normal(0,1,15))

Random number between 1 and 15: [ 0.04837504 -2.3251656  -0.80460365  0.24108686  0.05153751 -0.52284464
  0.12451998 -2.66631649 -2.45123344 -0.29977023 -0.46710441 -1.49501764
 -0.19405074  0.76354941  0.10284048]


# 19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.


In [126]:
import numpy as np
num = np.arange(15,55)
print("Random number between 1 and 15:",num[1:-1])

Random number between 1 and 15: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


# 20. Write a NumPy program to create a 3X4 array using and iterate over it.


In [16]:
import numpy as np
arr = np.array([[10,10,10,7],[1,2,3,4],[2,3,4,5]])
for i  in np.nditer(arr):
    print(i)

10
10
10
7
1
2
3
4
2
3
4
5


# 21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [130]:
import numpy as np
num = np.linspace(5,50,10)
print("Vector:",num)

Vector: [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


# 22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.


In [1]:
import numpy as np
arr = np.arange(0,20)
for i in arr[9:16]:
    arr[i] = arr[i]*(-1)
print(arr)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


## 23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [2]:
import numpy as np
num = np.random.randint(0,10,5)
print(num)

[6 7 7 4 3]


## 24. Write a NumPy program to multiply the values of two given vectors.


In [3]:
import numpy as np
num1 = np.array([1,2,3,4,5])
num2 = np.array([1,2,3,4,5])
print(num1*num2)

[ 1  4  9 16 25]


## 25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [11]:
import numpy as np
arr = np.arange(10,22).reshape(3,4)
print(arr)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


## 26. Write a NumPy program to find the number of rows and columns of a given matrix.


In [22]:
import numpy as np
arr = np.array([[10,22,23,24],[12,23,43,1]])
print(arr.shape)

(2, 4)


## 27. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

In [24]:
import numpy as np
a=np.identity(3)
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [138]:
import numpy as np
arr = np.zeros((10,10))
arr[:,:]=1
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [147]:
import numpy as np
arr = np.zeros((5,5))
np.fill_diagonal(arr,[1,2,3,4,5])
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


## 30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [158]:
import numpy as np
arr = np.zeros((4,4))
arr[::2,1::2] = 1
arr[1::2,::2] = 1
print(arr)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


## 31. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [173]:
import numpy as np
arr = np.random.random((3,3,3))
print(arr)

[[[0.98057847 0.93796687 0.48722678]
  [0.99457117 0.66505901 0.98720579]
  [0.18508584 0.99335156 0.72725126]]

 [[0.99828456 0.17706401 0.37609951]
  [0.45857924 0.98744397 0.77321963]
  [0.65891977 0.11727575 0.52123424]]

 [[0.60316764 0.57957606 0.05586224]
  [0.05044067 0.41244286 0.92522521]
  [0.2614176  0.97664826 0.14579929]]]


## 32. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.


In [180]:
import numpy as np
arr = np.array([[1,2,3,4,5],[2,31,23,21,23]])
print(arr)
print("Sum of coloumns:",(np.sum(arr,axis=0)))
print("Sum of rows:",(np.sum(arr,axis=1)))

[[ 1  2  3  4  5]
 [ 2 31 23 21 23]]
Sum of coloumns: [ 3 33 26 25 28]
Sum of rows: [ 15 100]


## 33. Write a NumPy program to compute the inner product of two given vectors.

In [185]:
import numpy as np
arr1 = np.array([[1,2],[2,31]])
arr2 = np.array([[1,2],[2,3]])
print("Product: \n",np.dot(arr1,arr2))

Product: 
 [[ 5  8]
 [64 97]]


## 34. Write a NumPy program to add a vector to each row of a given matrix.

In [188]:
import numpy as np
arr1 = np.array([[1,2],[2,31]])
arr2 = np.array([[1,2],[2,3]])
print("Sum: \n",arr1+arr2)

Sum: 
 [[ 2  4]
 [ 4 34]]


## 35. Write a NumPy program to save a given array to a binary file .


In [244]:
import numpy as np
arr1 = np.array([1,2,2,31])
arr2 = np.asarray(arr1,dtype='int')
with open("numpy.txt",'wb+') as fp:        
    for i in arr2:
        fp.write(i)
 

In [238]:
with open("numpy.txt",'rb+') as fp: 
    x=fp.read(x)
    print(x)

TypeError: argument should be integer or None, not 'bytes'

## 36. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.


In [247]:
import numpy as np
arr = np.array([1,2,2,31])
np.savetxt('new.txt',arr)


In [250]:
import numpy as np
arr = np.array([1,2,2,31])
np.savez('new',arr)
